/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-12-03 at 22:15:00 UTC 
 * Modify at your own risk.
 */

package com.google.samplesolutions.mobileassistant.videoendpoint.model;

/**
 * Model definition for Video.
 *
 * <p>
 * This is the Java data model class that specifies how to parse/serialize into
 * the JSON that is transmitted over HTTP when working with the videoendpoint.
 * For a detailed explanation see: <a href=
 * "http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Video extends com.google.api.client.json.GenericJson {

	/**
	 * The value may be {@code null}.
	 */
	@com.google.api.client.util.Key
	private java.lang.String category;

	/**
	 * The value may be {@code null}.
	 */
	@com.google.api.client.util.Key
	private java.lang.Integer ffwdtime;

	/**
	 * The value may be {@code null}.
	 */
	@com.google.api.client.util.Key
	private Key key;

	/**
	 * The value may be {@code null}.
	 */
	@com.google.api.client.util.Key
	private java.lang.Double popularity;

	/**
	 * The value may be {@code null}.
	 */
	@com.google.api.client.util.Key
	private java.lang.String tag;

	/**
	 * The value may be {@code null}.
	 */
	@com.google.api.client.util.Key
	private java.lang.Integer viewCount;

	/**
	 * The value may be {@code null}.
	 */
	@com.google.api.client.util.Key
	private java.lang.Integer ytviewCount;

	/**
	 * @return value or {@code null} for none
	 */
	public java.lang.String getCategory() {
		return category;
	}

	/**
	 * @param category
	 *            category or {@code null} for none
	 */
	public Video setCategory(java.lang.String category) {
		this.category = category;
		return this;
	}

	/**
	 * @return value or {@code null} for none
	 */
	public java.lang.Integer getFfwdtime() {
		return ffwdtime;
	}

	/**
	 * @param ffwdtime
	 *            ffwdtime or {@code null} for none
	 */
	public Video setFfwdtime(java.lang.Integer ffwdtime) {
		this.ffwdtime = ffwdtime;
		return this;
	}

	/**
	 * @return value or {@code null} for none
	 */
	public Key getKey() {
		return key;
	}

	/**
	 * @param key
	 *            key or {@code null} for none
	 */
	public Video setKey(Key key) {
		this.key = key;
		return this;
	}

	/**
	 * @return value or {@code null} for none
	 */
	public java.lang.Double getPopularity() {
		return popularity;
	}

	/**
	 * @param popularity
	 *            popularity or {@code null} for none
	 */
	public Video setPopularity(java.lang.Double popularity) {
		this.popularity = popularity;
		return this;
	}

	/**
	 * @return value or {@code null} for none
	 */
	public java.lang.String getTag() {
		return tag;
	}

	/**
	 * @param tag
	 *            tag or {@code null} for none
	 */
	public Video setTag(java.lang.String tag) {
		this.tag = tag;
		return this;
	}

	/**
	 * @return value or {@code null} for none
	 */
	public java.lang.Integer getViewCount() {
		return viewCount;
	}

	/**
	 * @param viewCount
	 *            viewCount or {@code null} for none
	 */
	public Video setViewCount(java.lang.Integer viewCount) {
		this.viewCount = viewCount;
		return this;
	}

	/**
	 * @return value or {@code null} for none
	 */
	public java.lang.Integer getYtviewCount() {
		return ytviewCount;
	}

	/**
	 * @param ytviewCount
	 *            ytviewCount or {@code null} for none
	 */
	public Video setYtviewCount(java.lang.Integer ytviewCount) {
		this.ytviewCount = ytviewCount;
		return this;
	}

	@Override
	public Video set(String fieldName, Object value) {
		return (Video) super.set(fieldName, value);
	}

	@Override
	public Video clone() {
		return (Video) super.clone();
	}

}
