/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-12-03 at 22:14:57 UTC 
 * Modify at your own risk.
 */

package com.google.samplesolutions.mobileassistant.userendpoint.model;

/**
 * Model definition for User.
 *
 * <p>
 * This is the Java data model class that specifies how to parse/serialize into
 * the JSON that is transmitted over HTTP when working with the userendpoint.
 * For a detailed explanation see: <a href=
 * "http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class User extends com.google.api.client.json.GenericJson {

	/**
	 * The value may be {@code null}.
	 */
	@com.google.api.client.util.Key
	private java.util.List<java.lang.String> categories;

	/**
	 * The value may be {@code null}.
	 */
	@com.google.api.client.util.Key
	private java.lang.String email;

	/**
	 * The value may be {@code null}.
	 */
	@com.google.api.client.util.Key
	private java.util.List<java.lang.String> favorites;

	/**
	 * The value may be {@code null}.
	 */
	@com.google.api.client.util.Key
	private Key key;

	/**
	 * The value may be {@code null}.
	 */
	@com.google.api.client.util.Key("last_seen")
	private com.google.api.client.util.DateTime lastSeen;

	/**
	 * The value may be {@code null}.
	 */
	@com.google.api.client.util.Key
	private java.lang.String name;

	/**
	 * The value may be {@code null}.
	 */
	@com.google.api.client.util.Key
	private java.lang.String password;

	/**
	 * The value may be {@code null}.
	 */
	@com.google.api.client.util.Key("seen_videos")
	private java.util.List<java.lang.String> seenVideos;

	/**
	 * The value may be {@code null}.
	 */
	@com.google.api.client.util.Key("sign_up_date")
	private com.google.api.client.util.DateTime signUpDate;

	/**
	 * @return value or {@code null} for none
	 */
	public java.util.List<java.lang.String> getCategories() {
		return categories;
	}

	/**
	 * @param categories
	 *            categories or {@code null} for none
	 */
	public User setCategories(java.util.List<java.lang.String> categories) {
		this.categories = categories;
		return this;
	}

	/**
	 * @return value or {@code null} for none
	 */
	public java.lang.String getEmail() {
		return email;
	}

	/**
	 * @param email
	 *            email or {@code null} for none
	 */
	public User setEmail(java.lang.String email) {
		this.email = email;
		return this;
	}

	/**
	 * @return value or {@code null} for none
	 */
	public java.util.List<java.lang.String> getFavorites() {
		return favorites;
	}

	/**
	 * @param favorites
	 *            favorites or {@code null} for none
	 */
	public User setFavorites(java.util.List<java.lang.String> favorites) {
		this.favorites = favorites;
		return this;
	}

	/**
	 * @return value or {@code null} for none
	 */
	public Key getKey() {
		return key;
	}

	/**
	 * @param key
	 *            key or {@code null} for none
	 */
	public User setKey(Key key) {
		this.key = key;
		return this;
	}

	/**
	 * @return value or {@code null} for none
	 */
	public com.google.api.client.util.DateTime getLastSeen() {
		return lastSeen;
	}

	/**
	 * @param lastSeen
	 *            lastSeen or {@code null} for none
	 */
	public User setLastSeen(com.google.api.client.util.DateTime lastSeen) {
		this.lastSeen = lastSeen;
		return this;
	}

	/**
	 * @return value or {@code null} for none
	 */
	public java.lang.String getName() {
		return name;
	}

	/**
	 * @param name
	 *            name or {@code null} for none
	 */
	public User setName(java.lang.String name) {
		this.name = name;
		return this;
	}

	/**
	 * @return value or {@code null} for none
	 */
	public java.lang.String getPassword() {
		return password;
	}

	/**
	 * @param password
	 *            password or {@code null} for none
	 */
	public User setPassword(java.lang.String password) {
		this.password = password;
		return this;
	}

	/**
	 * @return value or {@code null} for none
	 */
	public java.util.List<java.lang.String> getSeenVideos() {
		return seenVideos;
	}

	/**
	 * @param seenVideos
	 *            seenVideos or {@code null} for none
	 */
	public User setSeenVideos(java.util.List<java.lang.String> seenVideos) {
		this.seenVideos = seenVideos;
		return this;
	}

	/**
	 * @return value or {@code null} for none
	 */
	public com.google.api.client.util.DateTime getSignUpDate() {
		return signUpDate;
	}

	/**
	 * @param signUpDate
	 *            signUpDate or {@code null} for none
	 */
	public User setSignUpDate(com.google.api.client.util.DateTime signUpDate) {
		this.signUpDate = signUpDate;
		return this;
	}

	@Override
	public User set(String fieldName, Object value) {
		return (User) super.set(fieldName, value);
	}

	@Override
	public User clone() {
		return (User) super.clone();
	}

}
